import { dirname, join } from 'node:path'
import { fileURLToPath } from 'node:url'

const HERE = dirname(fileURLToPath(import.meta.url))

/** packages/pipeline/src/lib -> repo root */
export const REPO_ROOT = join(HERE, '..', '..', '..', '..')

/** Tier 1: raw snapshots. Generated, committed, never hand-edited. */
export const SOURCES_DIR = join(REPO_ROOT, 'sources')
/** Tier 2: hand-authored knowledge. Never generated. */
export const CURATED_DIR = join(REPO_ROOT, 'curated')
/** Tier 3: normalised entities. Generated, committed, never hand-edited. */
export const DATA_DIR = join(REPO_ROOT, 'data')

/**
 * Game art, under attribution. Generated by `assets:fetch`, committed, never
 * hand-edited — and never referenced from `data/`.
 *
 * The single-directory rule is load-bearing: `git rm -r assets/game` plus a
 * rebuild is the entire takedown procedure. See docs/DATA-POLICY.md.
 */
export const ASSETS_DIR = join(REPO_ROOT, 'assets', 'game')
export const ASSETS_MANIFEST = join(ASSETS_DIR, 'manifest.json')

/**
 * Intermediates, emitted schema and generated reports. Gitignored.
 *
 * The reports and the emitted JSON Schema used to land in `docs/`, which is no
 * longer committed. A generated file inside an untracked notes folder is
 * indistinguishable from a hand-written one, and it left CI reading a path that
 * is not part of the repo. They are build output, so they live with the build
 * output — `docs/` is hand-written notes and nothing in the pipeline writes
 * there.
 */
export const BUILD_DIR = join(REPO_ROOT, 'build')
export const REPORTS_DIR = join(BUILD_DIR, 'reports')
export const SCHEMA_DIR = join(BUILD_DIR, 'schema')
/**
 * The web app's static root. Vite copies it into `dist/` verbatim.
 *
 * Only generated output goes in here — `data/`, `assets/game/` and `guide/` are
 * all gitignored build products. The one committed file is `favicon.svg`.
 */
export const WEB_PUBLIC_DIR = join(REPO_ROOT, 'apps', 'web', 'public')

/** Shipped bundle the PWA fetches. Gitignored. */
export const SHIP_DIR = join(WEB_PUBLIC_DIR, 'data')

/**
 * The static, JS-free guide: one HTML page per record, for crawlers.
 *
 * Gitignored, and rewritten wholesale on every `build:seo` — so a renamed
 * record cannot leave a stale page behind, and nothing hand-written may live
 * here. Deleting this directory removes the entire SEO surface, which is the
 * point: same one-directory discipline as `assets/game/`.
 */
export const GUIDE_DIR = join(WEB_PUBLIC_DIR, 'guide')
/** Packed atlases and portraits the PWA fetches. Gitignored build output. */
export const ASSETS_SHIP_DIR = join(REPO_ROOT, 'apps', 'web', 'public', 'assets', 'game')

/** HTTP response cache for the wiki fetcher, so re-runs are incremental. */
export const CACHE_DIR = join(REPO_ROOT, '.cache')
