import { dirname, join } from 'node:path'
import { fileURLToPath } from 'node:url'

const HERE = dirname(fileURLToPath(import.meta.url))

/** packages/pipeline/src/lib -> repo root */
export const REPO_ROOT = join(HERE, '..', '..', '..', '..')

/** Tier 1: raw snapshots. Generated, committed, never hand-edited. */
export const SOURCES_DIR = join(REPO_ROOT, 'sources')
/** Tier 2: hand-authored knowledge. Never generated. */
export const CURATED_DIR = join(REPO_ROOT, 'curated')
/** Tier 3: normalised entities. Generated, committed, never hand-edited. */
export const DATA_DIR = join(REPO_ROOT, 'data')

/**
 * Game art, under attribution. Generated by `assets:fetch`, committed, never
 * hand-edited — and never referenced from `data/`.
 *
 * The single-directory rule is load-bearing: `git rm -r assets/game` plus a
 * rebuild is the entire takedown procedure. See docs/DATA-POLICY.md.
 */
export const ASSETS_DIR = join(REPO_ROOT, 'assets', 'game')
export const ASSETS_MANIFEST = join(ASSETS_DIR, 'manifest.json')

/** Intermediates and reports. Gitignored. */
export const BUILD_DIR = join(REPO_ROOT, 'build')
export const DOCS_DIR = join(REPO_ROOT, 'docs')
export const SCHEMA_DIR = join(DOCS_DIR, 'schema')
/** Shipped bundle the PWA fetches. Gitignored. */
export const SHIP_DIR = join(REPO_ROOT, 'apps', 'web', 'public', 'data')
/** Packed atlases and portraits the PWA fetches. Gitignored build output. */
export const ASSETS_SHIP_DIR = join(REPO_ROOT, 'apps', 'web', 'public', 'assets', 'game')

/** HTTP response cache for the wiki fetcher, so re-runs are incremental. */
export const CACHE_DIR = join(REPO_ROOT, '.cache')
