/**
 * `ATTRIBUTION.md`, generated from the manifest.
 *
 * Generated rather than written, because a hand-maintained credit file is a
 * credit file that is wrong. It regenerates as part of `build:ship` and is
 * covered by the determinism check, so it cannot quietly drift out of step with
 * what the repository actually contains — which for an attribution document is
 * the entire point.
 */
import { writeFile } from 'node:fs/promises'
import { join } from 'node:path'
import { REPO_ROOT } from '../lib/paths.js'
import { type AssetEntry, ATTRIBUTION_TEXT, readManifestOrEmpty } from './manifest.js'

const FAMILY_TITLES: Record<string, string> = {
  item: 'Items',
  villager: 'Villager icons',
  portrait: 'Villager portraits',
  monster: 'Monsters',
  skill: 'Skills',
  festival: 'Festivals',
  ui: 'Interface',
}

/** Escape the pipes and brackets that would otherwise break a Markdown table. */
const cell = (text: string): string => text.replace(/\|/g, '\\|')

export function renderAttribution(assets: AssetEntry[], source: string): string {
  const byFamily = new Map<string, AssetEntry[]>()
  for (const asset of assets) {
    byFamily.set(asset.family, [...(byFamily.get(asset.family) ?? []), asset])
  }

  const lines: string[] = [
    '# Attribution',
    '',
    '<!-- Generated by `pnpm build:ship`. Do not edit — edit the manifest’s source instead. -->',
    '',
    ATTRIBUTION_TEXT,
    '',
    'Fields of Mistria is made by NPC Studio — <https://fieldsofmistria.com>,',
    'and on Steam at <https://store.steampowered.com/app/2142790>.',
    '',
    'This project is a free, non-commercial fan work. It is not affiliated with,',
    'endorsed by, or connected to NPC Studio in any way. **Attribution does not',
    'create a licence**: the files listed below are used under attribution because',
    'this is the kind of fan project NPC Studio has been tolerant toward, and they',
    'will be removed on request from the rights holder — open an issue at',
    '<https://github.com/ChristoSmuts/mistria-codex/issues>.',
    '',
    'Every file lives under `assets/game/` and is listed here, so removing all of',
    'it is `git rm -r assets/game` and a rebuild.',
    '',
    `All files were fetched from the community wiki at <${source}>, which hosts them`,
    'and does not own them. The wiki’s **text** is CC BY-SA; the game’s **art** is not,',
    'and nothing in this repository treats it as though it were.',
    '',
    `**${assets.length} files.**`,
    '',
  ]

  for (const family of Object.keys(FAMILY_TITLES)) {
    const entries = byFamily.get(family)
    if (entries === undefined || entries.length === 0) continue

    lines.push(
      `## ${FAMILY_TITLES[family]} (${entries.length})`,
      '',
      '| In this repo | Original filename | Source |',
      '| --- | --- | --- |',
    )
    for (const asset of [...entries].sort((a, b) => a.file.localeCompare(b.file))) {
      lines.push(
        `| \`${cell(asset.file)}\` | ${cell(asset.source_file)} | [file page](${asset.source_url}) |`,
      )
    }
    lines.push('')
  }

  return lines.join('\n')
}

export async function writeAttribution(): Promise<number> {
  const manifest = await readManifestOrEmpty()
  const text = renderAttribution(manifest.assets, manifest.source)
  await writeFile(join(REPO_ROOT, 'ATTRIBUTION.md'), text, 'utf8')
  return manifest.assets.length
}
