/**
 * The asset register.
 *
 * `assets/game/manifest.json` is the single source of truth for every piece of
 * game art in this repository, and the reason a takedown is one deletion rather
 * than an archaeology project. Two properties make that true, and both are
 * enforced by `pnpm validate`:
 *
 * 1. **A file under `assets/game/` that is not listed here is an error.** So is a
 *    listing with no file. Either drift makes the register a lie, and a register
 *    nobody can trust is worse than none, because everyone downstream assumes it
 *    held.
 * 2. **`data/` never names an asset.** The `icon_key` -> sprite link lives only
 *    here, so deleting `assets/` orphans nothing and breaks no schema.
 *
 * See docs/DATA-POLICY.md for the policy this serves.
 */
import { readFile } from 'node:fs/promises'
import { z } from 'zod'
import { ASSETS_MANIFEST } from '../lib/paths.js'

/**
 * Which family an asset belongs to, which decides what it is packed into.
 *
 * `portrait` is the odd one out on purpose: portraits are large and looked at one
 * at a time, so they ship as individual lazily-loaded files rather than being
 * packed into a sheet with 1,133 32-pixel sprites.
 */
export const AssetFamily = z.enum([
  'item',
  'villager',
  'portrait',
  'monster',
  'skill',
  'festival',
  'ui',
  // Loose files, like portraits: the world map is 5442x3599 and the logo is a
  // banner — neither belongs in a sheet of 32-pixel sprites.
  'map',
  'brand',
])
export type AssetFamily = z.infer<typeof AssetFamily>

/** Families packed into atlases, in the order sheets are emitted. */
export const ATLAS_FAMILIES: readonly AssetFamily[] = [
  'item',
  'villager',
  'monster',
  'skill',
  'festival',
  'ui',
]

/** Families shipped as individual lazily-fetched files. */
export const LOOSE_FAMILIES: readonly AssetFamily[] = ['portrait', 'map', 'brand']

export const AssetEntry = z.object({
  /** Ours: `item/copper-ore`. Stable across a re-fetch. */
  key: z.string(),
  family: AssetFamily,
  /** Relative to `assets/game/`, forward slashes on every platform. */
  file: z.string(),
  /** Theirs, verbatim, in MediaWiki's canonical spelling. Credit needs the real name. */
  source_file: z.string(),
  source_url: z.string(),
  /** Date only. A timestamp would churn the manifest on every re-fetch. */
  fetched_at: z.string(),
  sha256: z.string(),
  bytes: z.number().int(),
  width: z.number().int(),
  height: z.number().int(),
  /**
   * Every record that wants this sprite. More than one is normal — two items can
   * share an icon, which is why the manifest is keyed by file and not by record.
   */
  icon_keys: z.array(z.string()),
})
export type AssetEntry = z.infer<typeof AssetEntry>

export const AssetManifest = z.object({
  _comment: z.array(z.string()).optional(),
  attribution: z.string(),
  source: z.string(),
  assets: z.array(AssetEntry),
})
export type AssetManifest = z.infer<typeof AssetManifest>

/** The attribution line, verbatim, in the register itself as well as in the UI. */
export const ATTRIBUTION_TEXT =
  'This is an unofficial fan-made companion app. All game assets, sprites, UI ' +
  'graphics, and character designs are the sole property of NPC Studio. We do ' +
  'not claim ownership of these assets. Full credit goes to the creators at NPC ' +
  'Studio.'

export const MANIFEST_COMMENT: readonly string[] = [
  'Every piece of game art in this repository, and where it came from.',
  '',
  'Generated by `pnpm assets:fetch`. Never hand-edited — an entry added by hand',
  'has no file behind it and validate will say so.',
  '',
  'These sprites are the property of NPC Studio. They are here under attribution',
  'as part of a free, non-commercial fan project; attribution is not a licence.',
  'To remove them: `git rm -r assets/game && pnpm build:ship`. Keeping that a',
  'one-line procedure is a hard constraint — see docs/DATA-POLICY.md.',
]

export async function readManifest(): Promise<AssetManifest> {
  const raw = await readFile(ASSETS_MANIFEST, 'utf8')
  return AssetManifest.parse(JSON.parse(raw))
}

/** The manifest, or an empty one — for the first run, before anything is fetched. */
export async function readManifestOrEmpty(): Promise<AssetManifest> {
  try {
    return await readManifest()
  } catch {
    return {
      attribution: ATTRIBUTION_TEXT,
      source: 'https://fieldsofmistria.wiki.gg',
      assets: [],
    }
  }
}
