import { mkdir, writeFile } from 'node:fs/promises'
import { join } from 'node:path'
import { toSnakeId } from '@mistria/schema'
import { REPORTS_DIR } from '../lib/paths.js'
import type { Loaded } from './load.js'

/**
 * Write the id risk register.
 *
 * Every row here is a place where slugifying the display name produced
 * something the game does not call the item. Nothing on the wiki reveals these
 * — the id looks reasonable, resolves fine, and would only have surfaced when
 * the game files landed and every saved donation was keyed to a name that had
 * never existed.
 *
 * The register is generated rather than hand-kept, so it stays true when a
 * source is refreshed. Since G1 it also records the one thing worth knowing
 * about the extraction: the game and the v0.15.0 snapshot agreed everywhere they
 * overlapped, so **no id moved**. The report's job was to make a surprise
 * visible, and the absence of one is the result.
 */
interface IdItem {
  id: string
  name: string
  id_status: string
  former_ids: string[]
  game_version: string | null
  numeric_id_game_version: string | null
}

export async function writeIdDivergenceReport(loaded: Loaded): Promise<void> {
  const items = loaded.items.records as unknown as IdItem[]

  const confirmed = items.filter((i) => i.id_status === 'confirmed')
  const stale = items.filter((i) => i.id_status === 'confirmed_stale')
  const provisional = items.filter((i) => i.id_status === 'provisional')
  const named = [...confirmed, ...stale]
  const moved = named
    .filter((i) => i.former_ids.length > 0)
    .sort((a, b) => a.name.localeCompare(b.name))

  const gameVersion = confirmed.find((i) => i.game_version !== null)?.game_version
  const snapshot = named.find((i) => i.numeric_id_game_version !== null)?.numeric_id_game_version

  const lines: string[] = [
    '# Item id divergence',
    '',
    'Generated by `pnpm validate` — do not edit.',
    '',
    "Item ids are the game's internal snake_case names. Three things can settle one,",
    'and `id_status` says which did:',
    '',
    `- \`confirmed\` — read from the game's own files at v${gameVersion ?? '?'}.`,
    `- \`confirmed_stale\` — matched against the v${snapshot ?? '?'} datamining snapshot, which`,
    "  predates 1.0, so the name is the game's but may have moved since.",
    '- `provisional` — still `toSnakeId(displayName)`, because no source names it.',
    '',
    '| | count |',
    '| --- | ---: |',
    `| items | ${items.length} |`,
    `| named by the game (\`confirmed\`) | ${confirmed.length} |`,
    `| named only by the snapshot (\`confirmed_stale\`) | ${stale.length} |`,
    `| still a slug (\`provisional\`) | ${provisional.length} |`,
    `| **ids the slug got wrong** | **${moved.length}** |`,
    '',
    '## Why this file exists',
    '',
    'Each row below is an id that a naive slug would have got wrong, and that nothing',
    'in the wiki data could have revealed. User progress is keyed by these ids, so',
    'adopting them after release orphans a saved museum tracker; adopting them now',
    'costs nothing. The old id is kept in each record’s `former_ids`.',
    '',
    '## What the game files settled',
    '',
    'The point of running the extraction was to find out how much had moved since',
    `v${snapshot ?? '?'}. The answer is **nothing**: every name the snapshot supplied is`,
    "still the name the installed build uses, so no id changed and no user's progress",
    'needed migrating. What changed is confidence — those ids are now read from the',
    'game rather than from an archive of an older one.',
    '',
    'The `provisional` rows are the residual, and most of them are not a gap in the',
    'extraction. Animal cosmetics are items on the wiki and are not items in the game:',
    'they live in `ranching/animals/*.toml` under a `[cosmetics.*]` key, outside the',
    '`ItemId` enum entirely. Their ids are ours, and nothing in the game will ever',
    'confirm them — `pnpm validate` subtracts them and reports only what is left,',
    'because a warning that can never go green teaches everyone to skim past the',
    'ones that can.',
    '',
    '## Ids the slug got wrong',
    '',
    '| Item | was | is | settled by |',
    '| --- | --- | --- | --- |',
  ]

  for (const item of moved) {
    const by = item.id_status === 'confirmed' ? `game v${item.game_version ?? '?'}` : 'snapshot'
    lines.push(`| ${item.name} | \`${item.former_ids.join('`, `')}\` | \`${item.id}\` | ${by} |`)
  }

  lines.push('', '## Still guesses', '', '| Item | id |', '| --- | --- |')
  for (const item of provisional.sort((a, b) => a.name.localeCompare(b.name))) {
    // Only worth listing where the slug is the only thing we have; a name no
    // source carries is the normal case for content the archive never saw.
    lines.push(`| ${item.name} | \`${toSnakeId(item.name)}\` |`)
  }

  lines.push('')
  await mkdir(REPORTS_DIR, { recursive: true })
  await writeFile(join(REPORTS_DIR, 'id-divergence.md'), `${lines.join('\n')}\n`, 'utf8')
}
