import { mkdir, writeFile } from 'node:fs/promises'
import { join } from 'node:path'
import { toSnakeId } from '@mistria/schema'
import { DOCS_DIR } from '../lib/paths.js'
import type { Loaded } from './load.js'

/**
 * Write the id risk register.
 *
 * Every row here is a place where slugifying the display name produced
 * something the game does not call the item. Nothing on the wiki reveals these
 * — the id looks reasonable, resolves fine, and would only have surfaced when
 * the game files landed and every saved donation was keyed to a name that had
 * never existed.
 *
 * The register is generated rather than hand-kept, so it stays true when the
 * snapshot is refreshed, and it is the document to read before G1: it is the
 * list of ids that a real extraction is most likely to move again.
 */
interface IdItem {
  id: string
  name: string
  id_status: string
  former_ids: string[]
  numeric_id_game_version: string | null
}

export async function writeIdDivergenceReport(loaded: Loaded): Promise<void> {
  const items = loaded.items.records as unknown as IdItem[]

  const confirmed = items.filter((i) => i.id_status === 'confirmed_stale')
  const provisional = items.filter((i) => i.id_status === 'provisional')
  const moved = confirmed
    .filter((i) => i.former_ids.length > 0)
    .sort((a, b) => a.name.localeCompare(b.name))
  const version = confirmed.find((i) => i.numeric_id_game_version !== null)?.numeric_id_game_version

  const lines: string[] = [
    '# Item id divergence',
    '',
    'Generated by `pnpm validate` — do not edit.',
    '',
    `Item ids are the game's internal snake_case names. Where a datamining snapshot of`,
    `v${version ?? '?'} names an item, that name is the id and \`id_status\` is`,
    '`confirmed_stale`; where it does not, the id is still `toSnakeId(displayName)` and',
    '`id_status` is `provisional`.',
    '',
    `| | count |`,
    '| --- | ---: |',
    `| items | ${items.length} |`,
    `| named by the snapshot (\`confirmed_stale\`) | ${confirmed.length} |`,
    `| still a slug (\`provisional\`) | ${provisional.length} |`,
    `| **ids the slug got wrong** | **${moved.length}** |`,
    '',
    '## Why this file exists',
    '',
    'Each row below is an id that a naive slug would have got wrong, and that nothing',
    'in the wiki data could have revealed. User progress is keyed by these ids, so',
    'adopting them after release orphans a saved museum tracker; adopting them now',
    'costs nothing. The old id is kept in each record’s `former_ids`.',
    '',
    'The `provisional` rows are the residual risk: no snapshot names them, so their ids',
    'are still guesses and are the ones most likely to move again at G1.',
    '',
    '## Ids the slug got wrong',
    '',
    '| Item | was | is |',
    '| --- | --- | --- |',
  ]

  for (const item of moved) {
    lines.push(`| ${item.name} | \`${item.former_ids.join('`, `')}\` | \`${item.id}\` |`)
  }

  lines.push('', '## Still guesses', '', '| Item | id |', '| --- | --- |')
  for (const item of provisional.sort((a, b) => a.name.localeCompare(b.name))) {
    // Only worth listing where the slug is the only thing we have; a name the
    // snapshot simply does not carry is the normal case for 1.0 content.
    lines.push(`| ${item.name} | \`${toSnakeId(item.name)}\` |`)
  }

  lines.push('')
  await mkdir(DOCS_DIR, { recursive: true })
  await writeFile(join(DOCS_DIR, 'id-divergence.md'), `${lines.join('\n')}\n`, 'utf8')
}
